@echo off
chcp 65001 >nul
title OS Project: OS Navigator Edition
color 0b

set "file=part4.html"

echo ^<!DOCTYPE html^> > %file%
echo ^<html lang="en"^> >> %file%
echo ^<head^> >> %file%
echo ^<meta charset="UTF-8"^> >> %file%
echo ^<title^>OS Navigator - Full Content^</title^> >> %file%
echo ^<style^> >> %file%
echo body { font-family: 'Segoe UI', Arial, sans-serif; background-color: #f0f2f5; color: #333; margin: 0; padding: 0; } >> %file%
echo .header { background-color: #f8f9fa; padding: 30px 5%%; text-align: center; border-bottom: 4px solid cornflowerblue; width: 100%%; box-sizing:border-box} >> %file%
echo .container { background-color:white; max-width: 1150px; margin: 40px auto; padding: 30px; border-radius: 15px; box-shadow:0 10px 30px cornflowerblue; } >> %file%
echo h1 { color: navy; margin: 0; font-size: 28px; } >> %file%
echo h2 { color: cornflowerblue; border-bottom: 2px solid #eee; margin-top: 30px; padding-bottom: 10px; } >> %file%
echo h3 { color: navy; } >> %file%
echo b { color: royalblue; } >> %file%
echo .highlight { color: royalblue; font-weight: bold; } >> %file%
echo .diagram-box { display: flex; align-items: center; justify-content: center; margin: 30px 0; background: #fdfdfd; padding: 20px; border-radius: 12px; border: 1px dashed cornflowerblue; } >> %file%
echo .node { padding: 15px 25px; border: 2px solid navy; border-radius: 8px; font-weight: bold; color: navy; background: white; min-width: 100px; text-align: center; } >> %file%
echo .mmu-node { background: cornflowerblue; color: white; border-radius: 50%%; padding: 30px 10px; border: none; } >> %file%
echo .arrow { font-size: 30px; margin: 0 15px; color: cornflowerblue; } >> %file%
echo .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 20px; } >> %file%
echo .card-simple { background: #fafafa; border: 1px solid #eee; padding: 20px; border-radius: 12px; } >> %file%
echo .bit-map { background: #f8f9fa; padding: 15px; border-radius: 8px; font-family: monospace; color: #2ecc71; word-break: break-all; border: 1px dashed cornflowerblue; margin-top: 10px; } >> %file%
echo .video-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 20px; margin-top: 20px; } >> %file%
echo .video-card { background: #fafafa; border: 1px solid #eee; padding: 15px; border-radius: 12px; text-align: center; } >> %file%
echo video , iframe { border-radius: 5px; height: 225px !important; width: 100%%; background: #000; } >> %file%
echo .footer { text-align: center; padding: 20px; margin-top: 40px; border-top: 1px solid #eee; color: cornflowerblue; font-size: 12px; } >> %file%
echo .home-btn { position: fixed; top: 20px; right: 20px; z-index: 9999; background-color: navy; color: white; padding: 12px 20px; border-radius: 8px; text-decoration: none; font-weight: bold; border: 2px solid cornflowerblue; box-shadow: 0 4px 10px rgba(0,0,0,0.3); transition: 0.4s; } >> %file%
echo .back-btn-top { position: fixed; top: 20px; left: 20px; z-index: 9999; background-color: navy; color: white; padding: 12px 20px; border-radius: 8px; text-decoration: none; font-weight: bold; border: 2px solid cornflowerblue; box-shadow: 0 4px 10px rgba(0,0,0,0.3); transition: 0.4s; } >> %file%
echo .home-btn:hover, .back-btn-top:hover { background-color: royalblue; transform: translateY(-3px); box-shadow: 0 5px 15px cornflowerblue; color: white; } >> %file%
echo .quiz-redirect-btn { display: block; width: fit-content; margin: 40px auto 10px; background-color: navy; color: white; padding: 12px 25px; border-radius: 12px; text-decoration: none; font-weight: bold; border: 2px solid cornflowerblue; transition: 0.4s; text-align: center; } >> %file%
echo .quiz-redirect-btn:hover { background-color: royalblue; transform: translateY(-3px); box-shadow: 0 5px 15px cornflowerblue; color: white; } >> %file%
echo ^</style^> >> %file%
echo ^</head^> >> %file%
echo ^<body^> >> %file%

echo ^<a href="javascript:history.back()" class="back-btn-top"^>Back^</a^> >> %file%
echo ^<a href="..\home Page\home.html" class="home-btn"^>Home Page^</a^> >> %file%

echo ^<div class="header"^> >> %file%
echo ^<h1^>OS ^<span style="color: cornflowerblue;"^>NAVIGATOR^</span^>^</h1^> >> %file%
echo ^<p^>Operating Systems Theoretical Core^</p^> >> %file%
echo ^</div^> >> %file%

echo ^<div class="container"^> >> %file%

echo ^<h1 style="text-align:center; color:navy; margin-top:40px;"^>Memory Management Foundations^</h1^> >> %file%
echo ^<h2^>1. Memory Management Unit (MMU)^</h2^> >> %file%
echo ^<p^>The ^<b^>MMU^</b^> is a hardware component that handles the mapping between ^<b^>Logical Addresses^</b^> (generated by the CPU) and ^<b^>Physical Addresses^</b^> (actual locations in RAM).^</p^> >> %file%
echo ^<div class="diagram-box"^> >> %file%
echo ^<div class="node"^>CPU^<br^>^<small^>Logical^</small^>^</div^> >> %file%
echo ^<span class="arrow"^>&#10141;^</span^> >> %file%
echo ^<div class="node mmu-node"^>MMU^<br^>^<small^>Mapping^</small^>^</div^> >> %file%
echo ^<span class="arrow"^>&#10141;^</span^> >> %file%
echo ^<div class="node"^>RAM^<br^>^<small^>Physical^</small^>^</div^> >> %file%
echo ^</div^> >> %file%
echo ^<h2^>2. Swapping Strategy^</h2^> >> %file%
echo ^<p^>^<b^>Swapping^</b^> allows processes to be moved between main memory and a backing store (disk) to accommodate more programs.^</p^> >> %file%
echo ^<ul^> >> %file%
echo ^<li^>^<b^>Swap Out:^</b^> RAM ^&rarr; Disk^</li^> >> %file%
echo ^<li^>^<b^>Swap In:^</b^> Disk ^&rarr; RAM^</li^> >> %file%
echo ^</ul^> >> %file%
echo ^<h2^>3. Contiguous Memory Allocation^</h2^> >> %file%
echo ^<p^>Algorithms used to find a "hole" for a process:^</p^> >> %file%
echo table border="1" width="100%%" style="border-color:cornflowerblue; font-size:18px; text-align:left; border-collapse: collapse;" cellpadding="10"^> >> %file%
echo ^<tr style="background-color:royalblue; color:white;"^>^<th^>Algorithm^</th^>^<th^>Strategy^</th^>^</tr^> >> %file%
echo ^<tr^>^<td^>^<b^>First-Fit^</b^>^</td^>^<td^>Allocate the first hole that is big enough.^</td^>^</tr^> >> %file%
echo ^<tr^>^<td^>^<b^>Best-Fit^</b^>^</td^>^<td^>Allocate the smallest hole that is big enough.^</td^>^</tr^> >> %file%
echo ^<tr^>^<td^>^<b^>Worst-Fit^</b^>^</td^>^<td^>Allocate the largest available hole.^</td^>^</tr^> >> %file%
echo ^</table^> >> %file%
echo ^<h1 style="text-align:center; color:navy; margin-top:40px;"^>Advanced Virtual Memory ^& Paging^</h1^> >> %file%
echo ^<h2^>1. Page Table Structures^</h2^> >> %file%
echo ^<p^>^<span class="highlight"^>Hierarchical Paging:^</span^> Breaking the page table into multiple levels (e.g., 2-level paging) to avoid storing huge contiguous tables in memory.^</p^> >> %file%
echo ^<div class="diagram-box"^> >> %file%
echo Outer Page Table ^&rarr; Page of Page Table ^&rarr; Memory Frame >> %file%
echo ^</div^> >> %file%
echo ^<p^>^<span class="highlight"^>Hashed Page Table:^</span^> Common for address spaces ^> 32 bits. Virtual page numbers are hashed into a table entry.^</p^> >> %file%
echo ^<p^>^<span class="highlight"^>Inverted Page Table:^</span^> One entry for each real page (frame) in memory, reducing table size significantly.^</p^> >> %file%
echo ^<h2^>2. Segmentation with Paging^</h2^> >> %file%
echo ^<p^>Segmentation supports the ^<span class="highlight"^>user view^</span^> of memory (Main, Objects, Stack). By combining it with Paging, we divide segments into equal-sized pages, providing better memory allocation and protection.^</p^> >> %file%
echo ^<h2^>3. Page Replacement Algorithms^</h2^> >> %file%
echo ^<p^>When a ^<span class="highlight"^>Page Fault^</span^> occurs and memory is full, we must victimize a page:^</p^> >> %file%
echo ^<ul^> >> %file%
echo ^<li^>^<b^>Optimal:^</b^> Replace page that won't be used for the longest time.^</li^> >> %file%
echo ^<li^>^<b^>FIFO:^</b^> First-In, First-Out (Oldest page is replaced).^</li^> >> %file%
echo ^<li^>^<b^>LRU:^</b^> Least Recently Used (Replaces page not used for the longest backward distance).^</li^> >> %file%
echo ^<li^>^<b^>LFU:^</b^> Least Frequently Used (Based on reference count).^</li^> >> %file%
echo ^</ul^> >> %file%
echo ^<h1 style="text-align:center; color:navy; margin-top:40px;"^>File Access Methods^</h1^> >> %file%
echo ^<p^>^<b^>Sequential Access:^</b^> Information is processed in order, one record after the other.^</p^> >> %file%
echo ^<p^>^<b^>Direct Access:^</b^> Allows reading or writing records rapidly in no particular order.^</p^> >> %file%

echo ^<div class="grid"^> >> %file%
echo ^<div class="card-simple"^> >> %file%
echo ^<h3^>Allocation Methods^</h3^> >> %file%
echo ^<ul^>^<li^>^<b^>Contiguous^</b^>^</li^>^<li^>^<b^>Linked^</b^>^</li^>^<li^>^<b^>Indexed^</b^>^</li^>^</ul^> >> %file%
echo ^</div^> >> %file%
echo ^<div class="card-simple"^> >> %file%
echo ^<h3^>Free-Space Management^</h3^> >> %file%
echo ^<p^>Includes ^<b^>Bit Vectors^</b^>, ^<b^>Linked Lists^</b^>, and ^<b^>Counting^</b^>.^</p^> >> %file%
echo ^</div^> >> %file%
echo ^</div^> >> %file%

echo ^<h2^>Disk Allocation Table^</h2^> >> %file%
echo ^<table border="1" width="100%%" style="border-color:cornflowerblue; font-size:18px; text-align:left;" cellpadding="10"^> >> %file%
echo ^<tr style="background-color:royalblue;"^>^<th^>File^</th^>^<th^>Start^</th^>^<th^>Length^</th^>^</tr^> >> %file%
echo ^<tr^>^<td^>count^</td^>^<td^>0^</td^>^<td^>2^</td^>^</tr^> >> %file%
echo ^<tr^>^<td^>tr^</td^>^<td^>14^</td^>^<td^>3^</td^>^</tr^> >> %file%
echo ^<tr^>^<td^>mail^</td^>^<td^>19^</td^>^<td^>6^</td^>^</tr^> >> %file%
echo ^<tr^>^<td^>list^</td^>^<td^>28^</td^>^<td^>4^</td^>^</tr^> >> %file%
echo ^</table^> >> %file%

echo ^<h3 style="margin-top:30px;"^>Free Space Bit Vector^</h3^> >> %file%
echo ^<div class="bit-map"^>0011110011111100011000000111...^</div^> >> %file%

echo ^<h1 style="text-align:center; color:navy; margin-top:40px;"^>Video Lectures ^& Lab Demonstrations^</h1^> >> %file%
echo ^<div class="video-grid"^> >> %file%
echo ^<div class="video-card"^>^<h3^>Introduction^</h3^>^<iframe src="https://drive.google.com/file/d/1fZqv67N30skG5xiGPqF1_yWLjsTtA5ew/preview" width="640" height="480"^>^</iframe^>^</div^> >> %file%
echo ^<div class="video-card"^>^<h3^>Address Space^</h3^>^<iframe src="https://drive.google.com/file/d/10y0_C0dnUKsLJHVByDHGMeRYFkw5dWdP/preview" width="640" height="480"^>^</iframe^>^</div^> >> %file%
echo ^<div class="video-card"^>^<h3^>Allocation^</h3^>^<iframe src="https://drive.google.com/file/d/1MKod5jay4_aRpRAB37AIa9iP6k6n9w3c/preview" width="640" height="480"^>^</iframe^>^</div^> >> %file%
echo ^<div class="video-card"^>^<h3^>Paging Structures^</h3^>^<iframe src="https://drive.google.com/file/d/1jKLqV7qM21uQsn5q4vQ1NyGrTLA0pg7e/preview" width="640" height="480"^>^</iframe^>^</div^> >> %file%
echo ^<div class="video-card"^>^<h3^>Segmentation Lab^</h3^>^<iframe src="https://drive.google.com/file/d/1AXVX_d425X5__DIvgLGwk0UkZao6bCVw/preview" width="640" height="480"^>^</iframe^>^</div^> >> %file%
echo ^<div class="video-card"^>^<h3^>Replacement Algos^</h3^>^<iframe src="https://drive.google.com/file/d/1cpfnU34OSwR4N55dUCTnXHv6DIG_u-Hy/preview" width="640" height="480"^>^</iframe^>^</div^> >> %file%
echo ^<div class="video-card"^>^<h3^>File Systems Part 1^</h3^>^<iframe src="https://drive.google.com/file/d/18neaSWerbJU77WdfZEJ6jU9adsLd2qbo/preview" width="640" height="480"^>^</iframe^>^</div^> >> %file%
echo ^<div class="video-card"^>^<h3^>File Systems Part 2^</h3^>^<iframe src="https://drive.google.com/file/d/1zVEKiPv7xbJWx1m8XU9FrTvZ1p2jHwLu/preview" width="640" height="480"^>^</iframe^>^</div^> >> %file%
echo ^</div^> >> %file%
echo ^<a href="quiz4.html" class="quiz-redirect-btn"^>Go To Quiz^</a^> >> %file%

echo ^</div^> >> %file%
echo ^<footer class="footer"^>Small Steps, Big Systems^</footer^> >> %file%
echo ^</div^> >> %file%

echo ^</body^> >> %file%
echo ^</html^> >> %file%

echo [DONE] OS Navigator - ALL CONTENT RESTORED
start "" "part4.html"