@echo off
chcp 65001 >nul
set "outfile=%~dp0Project_Final_Final.html"
set "thankfile=%~dp0Thank_You.html"

echo ^<!DOCTYPE html^> > "%thankfile%"
echo ^<html lang="en"^> >> "%thankfile%"
echo ^<head^> >> "%thankfile%"
echo ^<meta charset="UTF-8"^> >> "%thankfile%"
echo ^<style^> >> "%thankfile%"
echo @media screen and (max-width:768px){body{width:100vw!important;overflow-x:hidden!important;margin:0!important;padding:5px!important;}img,table,iframe{max-width:100%!important;height:auto!important;}} >> "%thankfile%"
echo body { font-family: 'Segoe UI', sans-serif; background-color: #f0f2f5; margin: 0; padding: 0; text-align: center; } >> "%thankfile%"
echo .header { background-color: white; padding: 50px 20px; text-align: center; border-bottom: 5px solid cornflowerblue; position: relative; } >> "%thankfile%"
echo .logo-left { position: absolute; left: 40px; top: 25px; width: 120px; height: 120px; border-radius: 50%%; border: 3px solid cornflowerblue; background: white; z-index: 1; } >> "%thankfile%"
echo .logo-right { position: absolute; right: 40px; top: 25px; width: 120px; height: 120px; border-radius: 50%%; border: 3px solid cornflowerblue; background: white; z-index: 1; } >> "%thankfile%"
echo .main-title { font-size: 55px; color: navy; font-weight: 900; margin: 0; text-transform: uppercase; letter-spacing: 4px; position: relative; z-index: 2; } >> "%thankfile%"
echo .nav-bar { background: navy; padding: 10px; text-align: center; } >> "%thankfile%"
echo .nav-btn { color: white; text-decoration: none; font-weight: bold; padding: 10px 25px; margin: 0 15px; border-radius: 8px; border: 2px solid cornflowerblue; transition: 0.4s; display: inline-block; font-size: 14px; cursor: pointer; background: navy; } >> "%thankfile%"
echo .nav-btn:hover { background: royalblue; transform: translateY(-3px); box-shadow: 0 5px 15px cornflowerblue; } >> "%thankfile%"
echo .container { background-color:white; max-width: 900px; margin: 40px auto; padding: 40px; border-radius: 20px; box-shadow: 0 10px 30px rgba(100,149,237,0.3); text-align: center; } >> "%thankfile%"
echo h1 { color: navy; border-bottom: 2px solid #eee; padding-bottom: 15px; } >> "%thankfile%"
echo .highlight-prof { color: royalblue; font-weight: 900; font-size: 24px; } >> "%thankfile%"
echo .prof-names { color: cornflowerblue; font-weight: bold; font-size: 24px; display: block; margin: 25px 0; border-top: 1px solid #eee; border-bottom: 1px solid #eee; padding: 15px 0; } >> "%thankfile%"
echo footer { margin-top: 40px; padding: 20px; color: cornflowerblue; font-size: 12px; text-align: center; } >> "%thankfile%"
echo ^</style^> >> "%thankfile%"
echo ^</head^> >> "%thankfile%"
echo ^<body^> >> "%thankfile%"
echo ^<header class="header"^> >> "%thankfile%"
echo ^<img src="logo1.png.jpeg" class="logo-left"^> >> "%thankfile%"
echo ^<img src="logo.png.jpeg" class="logo-right"^> >> "%thankfile%"
echo ^<div class="main-title"^>OS ^<span style="color:cornflowerblue;"^>NAVIGATOR^</span^>^</div^> >> "%thankfile%"
echo ^</header^> >> "%thankfile%"
echo ^<div class="nav-bar"^> >> "%thankfile%"
echo ^<button onclick="history.back()" class="nav-btn"^>Back^</button^> >> "%thankfile%"
echo ^<a href="..\home Page\home.html" class="nav-btn"^>Home Page^</a^> >> "%thankfile%"
echo ^</div^> >> "%thankfile%"
echo ^<div class="container"^> >> "%thankfile%"
echo ^<h1^>Dedication ^& Special Thanks^</h1^> >> "%thankfile%"
echo ^<div style="text-align: justify; font-size: 19px; line-height: 1.8; color: #444;"^> >> "%thankfile%"
echo ^<p^>We would like to extend our deepest gratitude and utmost respect to ^<span class="highlight-prof"^>Prof. Dr. Neveen Ghali^</span^>, Dean of the Faculty of Computers and Artificial Intelligence. Her visionary leadership and unwavering support have been the cornerstone of our academic excellence and the driving force behind the innovative environment we thrive in.^</p^> >> "%thankfile%"
echo ^</div^> >> "%thankfile%"
echo ^<span class="prof-names"^>Dr. Eman Hanafy ^| Dr. Asmaa Abdelmoniem^<br^>  Dr. Amany Ahmed ^| Dr.ola Elzein ^| Dr.Wafaa Ghonaim ^</span^> >> "%thankfile%"
echo ^<div style="text-align: justify; font-size: 19px; line-height: 1.8; color: #444;"^> >> "%thankfile%"
echo ^<p^>Our sincere appreciation goes to our esteemed professors mentioned above, who have mentored us with great patience and wisdom. Their dedication to sharing knowledge and their constant encouragement have not only shaped this project but also inspired our professional growth throughout this semester.^</p^> >> "%thankfile%"
echo ^</div^> >> "%thankfile%"
echo ^<p style="font-style: italic; color: #7f8c8d; font-size: 18px; margin-top:30px;"^>"Your guidance has been a light on our path to success. Thank you for believing in our potential."^</p^> >> "%thankfile%"
echo ^</div^> >> "%thankfile%"
echo ^<footer^>^<p^>Small Steps, Big Systems^</p^>^</footer^> >> "%thankfile%"
echo ^</body^> >> "%thankfile%"
echo ^</html^> >> "%thankfile%"
echo ^<!DOCTYPE html^> > "%outfile%"
echo ^<html lang="en"^> >> "%outfile%"
echo ^<head^> >> "%outfile%"
echo ^<meta charset="UTF-8"^> >> "%outfile%"
echo ^<style^> >> "%outfile%"
echo @media screen and (max-width:768px){body{width:100vw!important;overflow-x:hidden!important;margin:0!important;padding:5px!important;}img,table,iframe{max-width:100%!important;height:auto!important;}} >> "%outfile%"
echo body { font-family: 'Segoe UI', sans-serif; background-color: #f0f2f5; margin: 0; padding: 0; text-align: center; } >> "%outfile%"
echo .header { background-color: white; padding: 50px 20px; border-bottom: 5px solid cornflowerblue; position: relative; } >> "%outfile%"
echo .logo-left { position: absolute; left: 40px; top: 25px; width: 120px; height: 120px; border-radius: 50%%; border: 3px solid cornflowerblue; background: white; } >> "%outfile%"
echo .logo-right { position: absolute; right: 40px; top: 25px; width: 120px; height: 120px; border-radius: 50%%; border: 3px solid cornflowerblue; background: white; } >> "%outfile%"
echo .main-title { font-size: 55px; color: navy; font-weight: 900; margin: 0; text-transform: uppercase; letter-spacing: 4px; } >> "%outfile%"
echo .nav-bar { background: navy; padding: 10px; text-align: center; } >> "%outfile%"
echo .nav-btn { color: white; text-decoration: none; font-weight: bold; padding: 10px 25px; margin: 0 15px; border-radius: 8px; border: 2px solid cornflowerblue; transition: 0.4s; display: inline-block; font-size: 14px; cursor: pointer; background: navy; } >> "%outfile%"
echo .nav-btn:hover { background: royalblue; transform: translateY(-3px); box-shadow: 0 5px 15px cornflowerblue; } >> "%outfile%"
echo .container { max-width: 1000px; margin: 30px auto; padding: 20px; } >> "%outfile%"
echo .thanks-btn { display: block; width: fit-content; margin: 10px auto 30px; background: navy; color: white; padding: 15px 40px; border-radius: 50px; text-decoration: none; font-weight: bold; border: 2px solid cornflowerblue; transition: 0.4s; } >> "%outfile%"
echo .thanks-btn:hover { background: royalblue; transform: translateY(-5px); box-shadow: 0 10px 20px rgba(100,149,237,0.4); } >> "%outfile%"
echo .group-card { background: white; padding: 30px; border-radius: 15px; border-left: 12px solid navy; box-shadow: 0 10px 25px rgba(100,149,237,0.15); margin-bottom: 25px; text-align: left; } >> "%outfile%"
echo .group-title { color: navy; font-size: 22px; font-weight: bold; margin-bottom: 5px; display: block; } >> "%outfile%"
echo .group-task { color: cornflowerblue; font-style: italic; display: block; margin-bottom: 12px; border-bottom: 1px solid #eee; padding-bottom: 8px; } >> "%outfile%"
echo ul { list-style: none; padding: 0; } >> "%outfile%"
echo li { padding: 6px 0; font-size: 17px; color: #444; } >> "%outfile%"
echo li:before { content: "• "; color: cornflowerblue; font-weight: bold; } >> "%outfile%"
echo .content-section { background-color: white; padding: 35px; border-radius: 15px; box-shadow: 0 10px 30px rgba(100,149,237,0.2); margin-bottom: 30px; text-align: left; } >> "%outfile%"
echo footer { margin-top: 40px; padding: 20px; color: cornflowerblue; font-size: 12px; text-align: center; } >> "%outfile%"
echo ^</style^> >> "%outfile%"
echo ^</head^> >> "%outfile%"
echo ^<body^> >> "%outfile%"
echo ^<header class="header"^> >> "%outfile%"
echo ^<img src="logo1.png.jpeg" class="logo-left"^> >> "%outfile%"
echo ^<img src="logo.png.jpeg" class="logo-right"^> >> "%outfile%"
echo ^<div class="main-title"^>OS ^<span style="color:cornflowerblue;"^>NAVIGATOR^</span^>^</div^> >> "%outfile%"
echo ^</header^> >> "%outfile%"
echo ^<div class="nav-bar"^> >> "%outfile%"
echo ^<button onclick="history.back()" class="nav-btn"^>Back^</button^> >> "%outfile%"
echo ^<a href="..\home Page\home.html" class="nav-btn"^>Home Page^</a^> >> "%outfile%"
echo ^</div^> >> "%outfile%"
echo ^<div class="container"^> >> "%outfile%"
echo ^<h2 style="color: navy; margin-bottom: 30px;"^>Our Group's Adventures in Building This Project:^</h2^> >> "%outfile%"
echo ^<a href="Thank_You.html" class="thanks-btn"^>Special Dedication ^& Appreciation^</a^> >> "%outfile%"
echo ^<div class="content-section"^> >> "%outfile%"
echo ^<h3 style="color: royalblue; border-bottom: 2px solid royalblue; padding-bottom: 8px;"^>Who We Are:^</h3^> >> "%outfile%"
echo ^<p style="font-size:18px; line-height:1.7;"^>We are students from the ^<strong style="color:navy"^>Faculty of Computers and Artificial Intelligence, Al-Azhar University in Cairo (Computer Science Department)^</strong^>. To bring this project to life with the highest quality, we organized ourselves into a structured system consisting of five specialized groups. Each group had a dedicated leader, all coordinated by a ^<strong style="color:navy"^>"Leaders Group"^</strong^> that supervised the entire workflow.^</p^> >> "%outfile%"
echo ^<h3 style="color: royalblue; border-bottom: 2px solid royalblue; padding-bottom: 8px;"^>Our Vision:^</h3^> >> "%outfile%"
echo ^<p style="font-size:18px; line-height:1.7;"^>Our main goal was to create a comprehensive summary of the Operating Systems (OS) curriculum. ^<strong style="color:navy"^>This project was uniquely developed using Batch files (.bat) and HTML to provide a smooth and interactive experience.^</strong^>^</p^> >> "%outfile%"
echo ^</div^> >> "%outfile%"
echo ^<div class="group-card"^> >> "%outfile%"
echo ^<span class="group-title"^>Group A (Integration ^& Design)^</span^> >> "%outfile%"
echo ^<span class="group-task"^>Responsible for the Home Page, Final Page, code collection, and linking all project pages.^</span^> >> "%outfile%"
echo ^<ul^> >> "%outfile%"
echo ^<li^>Shahd Mahmoud Elsayed Ali Mostafa^</li^> >> "%outfile%"
echo ^<li^>Hagar Mohamed Essam Doash^</li^> >> "%outfile%"
echo ^<li^>Mariam Hamdy Mahmoud Ibrahim^</li^> >> "%outfile%"
echo ^<li^>Yasmin Ramy Abdelhameed Mansour^</li^> >> "%outfile%"
echo ^<li^>Hadeer Sabry Fawzy Ali^</li^> >> "%outfile%"
echo ^</ul^> >> "%outfile%"
echo ^</div^> >> "%outfile%"
echo ^<div class="group-card"^> >> "%outfile%"
echo ^<span class="group-title"^>Group B (Assessment)^</span^> >> "%outfile%"
echo ^<span class="group-task"^>Dedicated to developing the Interactive Quizzes section.^</span^> >> "%outfile%"
echo ^<ul^> >> "%outfile%"
echo ^<li^>Azza Mohamed Abdel Latif Al-Baz^</li^> >> "%outfile%"
echo ^<li^>Menna Mokhles Abdelmonem Heseen^</li^> >> "%outfile%"
echo ^<li^>Mariam Ahmed Abdelmonem Elwan^</li^> >> "%outfile%"
echo ^<li^>Malak Mohamed Tawkal Abd Elmoaty^</li^> >> "%outfile%"
echo ^</ul^> >> "%outfile%"
echo ^</div^> >> "%outfile%"
echo ^<div class="group-card"^> >> "%outfile%"
echo ^<span class="group-title"^>Group C (Curriculum Part I)^</span^> >> "%outfile%"
echo ^<span class="group-task"^>Focused on summarizing and explaining Part 1 ^& Part 2 of the OS curriculum.^</span^> >> "%outfile%"
echo ^<ul^> >> "%outfile%"
echo ^<li^>Heba Mesbah Mohamed Salama^</li^> >> "%outfile%"
echo ^<li^>Mayada Abd Elrahman Abd Elgawad Mohamed^</li^> >> "%outfile%"
echo ^<li^>Yara Elsayed Ramadan Hussein Mohamed^</li^> >> "%outfile%"
echo ^</ul^> >> "%outfile%"
echo ^</div^> >> "%outfile%"
echo ^<div class="group-card"^> >> "%outfile%"
echo ^<span class="group-title"^>Group D (Curriculum Part II)^</span^> >> "%outfile%"
echo ^<span class="group-task"^>Focused on summarizing and explaining Part 3 ^& Part 4 of the OS curriculum.^</span^> >> "%outfile%"
echo ^<ul^> >> "%outfile%"
echo ^<li^>Mai Abd Elfattah Abd Elhaleem^</li^> >> "%outfile%"
echo ^<li^>Menna Allah Ahmed Abdelreheem^</li^> >> "%outfile%"
echo ^<li^>Sohaila Ibrahim Elsherbiny Hamza^</li^> >> "%outfile%"
echo ^<li^>Heba Hamada Ebrahim Tamam^</li^> >> "%outfile%"
echo ^</ul^> >> "%outfile%"
echo ^</div^> >> "%outfile%"
echo ^<div class="group-card"^> >> "%outfile%"
echo ^<span class="group-title"^>Group E (Practical Labs)^</span^> >> "%outfile%"
echo ^<span class="group-task"^>Responsible for the Practical section, covering all lab implementations.^</span^> >> "%outfile%"
echo ^<ul^> >> "%outfile%"
echo ^<li^>Menna Hosaam Abd Elazeem Ali^</li^> >> "%outfile%"
echo ^<li^>Menna Allah Samy Mohamed Ahmed^</li^> >> "%outfile%"
echo ^<li^>Menna Elsayed Mohamed Abd Elshakoor^</li^> >> "%outfile%"
echo ^<li^>Aisha Mahmoud Marghany Mahmoud^</li^> >> "%outfile%"
echo ^</ul^> >> "%outfile%"
echo ^</div^> >> "%outfile%"
echo ^</div^> >> "%outfile%"
echo ^<footer^>^<p^>Small Steps, Big Systems^</p^>^</footer^> >> "%outfile%"
echo ^</body^> >> "%outfile%"
echo ^</html^> >> "%outfile%"

start "" "%outfile%"
exit